[package]
name = "xmlbufrw"
version = "0.1.0"
authors = ["Will Page <compenguy@gmail.com>"]

[dependencies]
encoding_rs = "0.8.13"
encodingbufrw = { git = "https://github.com/compenguy/encodingbufrw" }
